module.exports = {
  t_id: "R2023493",
  name: "The RSM Classic",
  players: [
    {
      p_id: "40115",
      player_name: "Adam Svensson",
      position: "1",
      round_1: "73",
      round_2: "64",
      round_3: "62",
      round_4: "64",
      total: "263",
      par_relative_score: "-19",
      points_earned: 500,
    },
    {
      p_id: "48699",
      player_name: "Callum Tarren",
      position: "T2",
      round_1: "64",
      round_2: "68",
      round_3: "69",
      round_4: "64",
      total: "265",
      par_relative_score: "-17",
      points_earned: 208.333,
    },
    {
      p_id: "51634",
      player_name: "Sahith Theegala",
      position: "T2",
      round_1: "68",
      round_2: "63",
      round_3: "68",
      round_4: "66",
      total: "265",
      par_relative_score: "-17",
      points_earned: 208.333,
    },
    {
      p_id: "27644",
      player_name: "Brian Harman",
      position: "T2",
      round_1: "67",
      round_2: "69",
      round_3: "64",
      round_4: "65",
      total: "265",
      par_relative_score: "-17",
      points_earned: 208.333,
    },
    {
      p_id: "27963",
      player_name: "Chris Stroud",
      position: "T5",
      round_1: "70",
      round_2: "66",
      round_3: "66",
      round_4: "65",
      total: "267",
      par_relative_score: "-15",
      points_earned: 93,
    },
    {
      p_id: "28252",
      player_name: "Seamus Power",
      position: "T5",
      round_1: "66",
      round_2: "68",
      round_3: "67",
      round_4: "66",
      total: "267",
      par_relative_score: "-15",
      points_earned: 93,
    },
    {
      p_id: "34076",
      player_name: "Joel Dahmen",
      position: "T5",
      round_1: "67",
      round_2: "64",
      round_3: "72",
      round_4: "64",
      total: "267",
      par_relative_score: "-15",
      points_earned: 93,
    },
    {
      p_id: "46340",
      player_name: "Alex Smalley",
      position: "T5",
      round_1: "67",
      round_2: "66",
      round_3: "67",
      round_4: "67",
      total: "267",
      par_relative_score: "-15",
      points_earned: 93,
    },
    {
      p_id: "47987",
      player_name: "Cole Hammer",
      position: "T5",
      round_1: "64",
      round_2: "66",
      round_3: "72",
      round_4: "65",
      total: "267",
      par_relative_score: "-15",
      points_earned: 0,
    },
    {
      p_id: "46441",
      player_name: "Robby Shelton",
      position: "T10",
      round_1: "68",
      round_2: "70",
      round_3: "65",
      round_4: "65",
      total: "268",
      par_relative_score: "-14",
      points_earned: 65.4,
    },
    {
      p_id: "36699",
      player_name: "Patrick Rodgers",
      position: "T10",
      round_1: "69",
      round_2: "65",
      round_3: "64",
      round_4: "70",
      total: "268",
      par_relative_score: "-14",
      points_earned: 65.4,
    },
    {
      p_id: "51766",
      player_name: "Wyndham Clark",
      position: "T10",
      round_1: "71",
      round_2: "65",
      round_3: "66",
      round_4: "66",
      total: "268",
      par_relative_score: "-14",
      points_earned: 65.4,
    },
    {
      p_id: "34374",
      player_name: "Erik Barnes",
      position: "T10",
      round_1: "70",
      round_2: "67",
      round_3: "65",
      round_4: "66",
      total: "268",
      par_relative_score: "-14",
      points_earned: 65.4,
    },
    {
      p_id: "34409",
      player_name: "David Lingmerth",
      position: "T10",
      round_1: "67",
      round_2: "65",
      round_3: "70",
      round_4: "66",
      total: "268",
      par_relative_score: "-14",
      points_earned: 65.4,
    },
    {
      p_id: "29289",
      player_name: "S.Y. Noh",
      position: "T15",
      round_1: "68",
      round_2: "64",
      round_3: "70",
      round_4: "67",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "51890",
      player_name: "Greyson Sigg",
      position: "T15",
      round_1: "66",
      round_2: "69",
      round_3: "70",
      round_4: "64",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "39324",
      player_name: "J.J. Spaun",
      position: "T15",
      round_1: "67",
      round_2: "68",
      round_3: "69",
      round_4: "65",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "40250",
      player_name: "Taylor Pendrith",
      position: "T15",
      round_1: "69",
      round_2: "66",
      round_3: "65",
      round_4: "69",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "55789",
      player_name: "Taylor Montgomery",
      position: "T15",
      round_1: "69",
      round_2: "66",
      round_3: "65",
      round_4: "69",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "56762",
      player_name: "Will Gordon",
      position: "T15",
      round_1: "69",
      round_2: "64",
      round_3: "68",
      round_4: "68",
      total: "269",
      par_relative_score: "-13",
      points_earned: 50,
    },
    {
      p_id: "48119",
      player_name: "Ben Taylor",
      position: "T21",
      round_1: "71",
      round_2: "65",
      round_3: "65",
      round_4: "69",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "49771",
      player_name: "J.T. Poston",
      position: "T21",
      round_1: "70",
      round_2: "67",
      round_3: "66",
      round_4: "67",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "29926",
      player_name: "Danny Lee",
      position: "T21",
      round_1: "70",
      round_2: "66",
      round_3: "66",
      round_4: "68",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "34256",
      player_name: "Andrew Putnam",
      position: "T21",
      round_1: "65",
      round_2: "65",
      round_3: "69",
      round_4: "71",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "35461",
      player_name: "Beau Hossler",
      position: "T21",
      round_1: "64",
      round_2: "67",
      round_3: "69",
      round_4: "70",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "33122",
      player_name: "Russell Knox",
      position: "T21",
      round_1: "67",
      round_2: "70",
      round_3: "66",
      round_4: "67",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "33413",
      player_name: "Ben Martin",
      position: "T21",
      round_1: "69",
      round_2: "64",
      round_3: "65",
      round_4: "72",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "33597",
      player_name: "Harry Higgs",
      position: "T21",
      round_1: "67",
      round_2: "63",
      round_3: "70",
      round_4: "70",
      total: "270",
      par_relative_score: "-12",
      points_earned: 36.625,
    },
    {
      p_id: "34099",
      player_name: "Harris English",
      position: "T29",
      round_1: "68",
      round_2: "68",
      round_3: "70",
      round_4: "65",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "29478",
      player_name: "Kevin Kisner",
      position: "T29",
      round_1: "70",
      round_2: "67",
      round_3: "67",
      round_4: "67",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "22405",
      player_name: "Justin Rose",
      position: "T29",
      round_1: "68",
      round_2: "67",
      round_3: "67",
      round_4: "69",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "54591",
      player_name: "Ben Griffin",
      position: "T29",
      round_1: "65",
      round_2: "71",
      round_3: "67",
      round_4: "68",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "40058",
      player_name: "Zac Blair",
      position: "T29",
      round_1: "67",
      round_2: "69",
      round_3: "68",
      round_4: "67",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "35901",
      player_name: "Paul Haley II",
      position: "T29",
      round_1: "68",
      round_2: "67",
      round_3: "67",
      round_4: "69",
      total: "271",
      par_relative_score: "-11",
      points_earned: 25.75,
    },
    {
      p_id: "39975",
      player_name: "Michael Kim",
      position: "T35",
      round_1: "67",
      round_2: "69",
      round_3: "69",
      round_4: "67",
      total: "272",
      par_relative_score: "-10",
      points_earned: 19.5,
    },
    {
      p_id: "27214",
      player_name: "Kevin Streelman",
      position: "T35",
      round_1: "68",
      round_2: "64",
      round_3: "68",
      round_4: "72",
      total: "272",
      par_relative_score: "-10",
      points_earned: 19.5,
    },
    {
      p_id: "32757",
      player_name: "Patton Kizzire",
      position: "T35",
      round_1: "67",
      round_2: "68",
      round_3: "70",
      round_4: "67",
      total: "272",
      par_relative_score: "-10",
      points_earned: 19.5,
    },
    {
      p_id: "59095",
      player_name: "Chris Gotterup",
      position: "T35",
      round_1: "65",
      round_2: "68",
      round_3: "71",
      round_4: "68",
      total: "272",
      par_relative_score: "-10",
      points_earned: 0,
    },
    {
      p_id: "30163",
      player_name: "Henrik Norlander",
      position: "T39",
      round_1: "67",
      round_2: "69",
      round_3: "70",
      round_4: "67",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "22371",
      player_name: "Aaron Baddeley",
      position: "T39",
      round_1: "69",
      round_2: "68",
      round_3: "68",
      round_4: "68",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "39546",
      player_name: "Keith Mitchell",
      position: "T39",
      round_1: "67",
      round_2: "68",
      round_3: "69",
      round_4: "69",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "47591",
      player_name: "Eric Cole",
      position: "T39",
      round_1: "69",
      round_2: "68",
      round_3: "70",
      round_4: "66",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "55454",
      player_name: "Carl Yuan",
      position: "T39",
      round_1: "70",
      round_2: "68",
      round_3: "69",
      round_4: "66",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "55708",
      player_name: "Hayden Buckley",
      position: "T39",
      round_1: "69",
      round_2: "66",
      round_3: "69",
      round_4: "69",
      total: "273",
      par_relative_score: "-9",
      points_earned: 14.5,
    },
    {
      p_id: "56630",
      player_name: "Akshay Bhatia",
      position: "45",
      round_1: "73",
      round_2: "63",
      round_3: "69",
      round_4: "69",
      total: "274",
      par_relative_score: "-8",
      points_earned: 0,
    },
    {
      p_id: "54783",
      player_name: "Dylan Wu",
      position: "T46",
      round_1: "70",
      round_2: "68",
      round_3: "70",
      round_4: "67",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "47993",
      player_name: "Denny McCarthy",
      position: "T46",
      round_1: "66",
      round_2: "70",
      round_3: "68",
      round_4: "71",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "47995",
      player_name: "Davis Riley",
      position: "T46",
      round_1: "68",
      round_2: "69",
      round_3: "69",
      round_4: "69",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "39335",
      player_name: "Kevin Roy",
      position: "T46",
      round_1: "69",
      round_2: "68",
      round_3: "68",
      round_4: "70",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "36799",
      player_name: "Stephan Jaeger",
      position: "T46",
      round_1: "67",
      round_2: "70",
      round_3: "71",
      round_4: "67",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "19803",
      player_name: "Ryan Armour",
      position: "T46",
      round_1: "70",
      round_2: "67",
      round_3: "73",
      round_4: "65",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "29535",
      player_name: "Brice Garnett",
      position: "T46",
      round_1: "68",
      round_2: "69",
      round_3: "69",
      round_4: "69",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "31557",
      player_name: "Jim Herman",
      position: "T46",
      round_1: "72",
      round_2: "65",
      round_3: "70",
      round_4: "68",
      total: "275",
      par_relative_score: "-7",
      points_earned: 8.75,
    },
    {
      p_id: "30692",
      player_name: "Scott Stallings",
      position: "T54",
      round_1: "70",
      round_2: "66",
      round_3: "67",
      round_4: "73",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "33974",
      player_name: "Dean Burmester",
      position: "T54",
      round_1: "66",
      round_2: "68",
      round_3: "71",
      round_4: "71",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "35617",
      player_name: "Martin Trainer",
      position: "T54",
      round_1: "70",
      round_2: "67",
      round_3: "67",
      round_4: "72",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "45242",
      player_name: "Kevin Yu",
      position: "T54",
      round_1: "72",
      round_2: "66",
      round_3: "69",
      round_4: "69",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "52374",
      player_name: "Brandon Wu",
      position: "T54",
      round_1: "70",
      round_2: "68",
      round_3: "67",
      round_4: "71",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "49453",
      player_name: "Trevor Cone",
      position: "T54",
      round_1: "69",
      round_2: "68",
      round_3: "68",
      round_4: "71",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "51414",
      player_name: "Brent Grant",
      position: "T54",
      round_1: "71",
      round_2: "67",
      round_3: "71",
      round_4: "67",
      total: "276",
      par_relative_score: "-6",
      points_earned: 5.538,
    },
    {
      p_id: "60004",
      player_name: "Jacob Bridgeman",
      position: "T54",
      round_1: "69",
      round_2: "67",
      round_3: "73",
      round_4: "67",
      total: "276",
      par_relative_score: "-6",
      points_earned: 0,
    },
    {
      p_id: "34610",
      player_name: "Matthias Schwab",
      position: "T62",
      round_1: "72",
      round_2: "66",
      round_3: "68",
      round_4: "71",
      total: "277",
      par_relative_score: "-5",
      points_earned: 4.5,
    },
    {
      p_id: "33408",
      player_name: "Tyson Alexander",
      position: "T62",
      round_1: "68",
      round_2: "69",
      round_3: "70",
      round_4: "70",
      total: "277",
      par_relative_score: "-5",
      points_earned: 4.5,
    },
    {
      p_id: "34255",
      player_name: "Joseph Bramlett",
      position: "T64",
      round_1: "68",
      round_2: "69",
      round_3: "72",
      round_4: "69",
      total: "278",
      par_relative_score: "-4",
      points_earned: 4.1,
    },
    {
      p_id: "53165",
      player_name: "Doc Redman",
      position: "T64",
      round_1: "70",
      round_2: "68",
      round_3: "73",
      round_4: "67",
      total: "278",
      par_relative_score: "-4",
      points_earned: 4.1,
    },
    {
      p_id: "50493",
      player_name: "Justin Suh",
      position: "66",
      round_1: "66",
      round_2: "68",
      round_3: "70",
      round_4: "75",
      total: "279",
      par_relative_score: "-3",
      points_earned: 3.8,
    },
    {
      p_id: "37338",
      player_name: "Zecheng Dou",
      position: "T67",
      round_1: "69",
      round_2: "67",
      round_3: "71",
      round_4: "74",
      total: "281",
      par_relative_score: "-1",
      points_earned: 3.5,
    },
    {
      p_id: "33410",
      player_name: "Andrew Landry",
      position: "T67",
      round_1: "75",
      round_2: "63",
      round_3: "72",
      round_4: "71",
      total: "281",
      par_relative_score: "-1",
      points_earned: 3.5,
    },
    {
      p_id: "39067",
      player_name: "MJ Daffue",
      position: "69",
      round_1: "70",
      round_2: "68",
      round_3: "70",
      round_4: "75",
      total: "283",
      par_relative_score: "+1",
      points_earned: 3.2,
    },
    {
      p_id: "37275",
      player_name: "Sam Ryder",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "47988",
      player_name: "Nick Hardy",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "51070",
      player_name: "Vincent Norrman",
      position: "CUT",
      round_1: "71",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "51349",
      player_name: "Nico Echavarria",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "50188",
      player_name: "S.H. Kim",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "32333",
      player_name: "Kevin Tway",
      position: "CUT",
      round_1: "70",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "30927",
      player_name: "Brendon Todd",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "35506",
      player_name: "Mackenzie Hughes",
      position: "CUT",
      round_1: "71",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "34563",
      player_name: "Chesson Hadley",
      position: "CUT",
      round_1: "69",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "35449",
      player_name: "Adam Long",
      position: "CUT",
      round_1: "71",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "34431",
      player_name: "Robert Streb",
      position: "CUT",
      round_1: "68",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "23108",
      player_name: "Matt Kuchar",
      position: "CUT",
      round_1: "70",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "20229",
      player_name: "Stewart Cink",
      position: "CUT",
      round_1: "70",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "23621",
      player_name: "Rory Sabbatini",
      position: "CUT",
      round_1: "70",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "25686",
      player_name: "Jason Dufner",
      position: "CUT",
      round_1: "70",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "29970",
      player_name: "Dylan Frittelli",
      position: "CUT",
      round_1: "71",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "58594",
      player_name: "Spencer Ralston",
      position: "CUT",
      round_1: "68",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "55893",
      player_name: "Samuel Stevens",
      position: "CUT",
      round_1: "72",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "139",
      par_relative_score: "-3",
      points_earned: 0,
    },
    {
      p_id: "28775",
      player_name: "Nate Lashley",
      position: "CUT",
      round_1: "70",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "19846",
      player_name: "Brian Gay",
      position: "CUT",
      round_1: "71",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "34466",
      player_name: "Peter Malnati",
      position: "CUT",
      round_1: "69",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "30926",
      player_name: "Chris Kirk",
      position: "CUT",
      round_1: "71",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "47347",
      player_name: "Adam Schenk",
      position: "CUT",
      round_1: "70",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "52411",
      player_name: "Kyle Westmoreland",
      position: "CUT",
      round_1: "72",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "45609",
      player_name: "Tyler Duncan",
      position: "CUT",
      round_1: "75",
      round_2: "65",
      round_3: null,
      round_4: null,
      total: "140",
      par_relative_score: "-2",
      points_earned: 0,
    },
    {
      p_id: "47667",
      player_name: "Conner Godsey",
      position: "CUT",
      round_1: "70",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "47983",
      player_name: "Chad Ramey",
      position: "CUT",
      round_1: "68",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "36871",
      player_name: "Matthew NeSmith",
      position: "CUT",
      round_1: "70",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "54628",
      player_name: "Lee Hodges",
      position: "CUT",
      round_1: "72",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "51491",
      player_name: "Brandon Matthews",
      position: "CUT",
      round_1: "72",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "34174",
      player_name: "John Huh",
      position: "CUT",
      round_1: "69",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "22056",
      player_name: "Cameron Percy",
      position: "CUT",
      round_1: "69",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "25818",
      player_name: "Scott Piercy",
      position: "CUT",
      round_1: "73",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "24024",
      player_name: "Zach Johnson",
      position: "CUT",
      round_1: "69",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "24140",
      player_name: "Sean O'Hair",
      position: "CUT",
      round_1: "69",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "29221",
      player_name: "Webb Simpson",
      position: "CUT",
      round_1: "67",
      round_2: "74",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "25198",
      player_name: "Francesco Molinari",
      position: "CUT",
      round_1: "67",
      round_2: "74",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "27974",
      player_name: "Sung Kang",
      position: "CUT",
      round_1: "72",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "28089",
      player_name: "Jason Day",
      position: "CUT",
      round_1: "74",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "57975",
      player_name: "Harry Hall",
      position: "CUT",
      round_1: "70",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "141",
      par_relative_score: "-1",
      points_earned: 0,
    },
    {
      p_id: "27770",
      player_name: "Camilo Villegas",
      position: "CUT",
      round_1: "75",
      round_2: "67",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "27095",
      player_name: "Nick Watney",
      position: "CUT",
      round_1: "73",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "12716",
      player_name: "Charley Hoffman",
      position: "CUT",
      round_1: "69",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "35110",
      player_name: "Brett Drewitt",
      position: "CUT",
      round_1: "76",
      round_2: "66",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "32640",
      player_name: "Troy Merritt",
      position: "CUT",
      round_1: "71",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "33948",
      player_name: "Byeong Hun An",
      position: "CUT",
      round_1: "71",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "54421",
      player_name: "Garrick Higgo",
      position: "CUT",
      round_1: "71",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "52513",
      player_name: "Carson Young",
      position: "CUT",
      round_1: "73",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "35879",
      player_name: "Kelly Kraft",
      position: "CUT",
      round_1: "72",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "47079",
      player_name: "Harrison Endycott",
      position: "CUT",
      round_1: "76",
      round_2: "66",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "40162",
      player_name: "Justin Lower",
      position: "CUT",
      round_1: "69",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "46414",
      player_name: "Aaron Rai",
      position: "CUT",
      round_1: "74",
      round_2: "68",
      round_3: null,
      round_4: null,
      total: "142",
      par_relative_score: "E",
      points_earned: 0,
    },
    {
      p_id: "51997",
      player_name: "Andrew Novak",
      position: "CUT",
      round_1: "71",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "143",
      par_relative_score: "+1",
      points_earned: 0,
    },
    {
      p_id: "35532",
      player_name: "Tom Hoge",
      position: "CUT",
      round_1: "71",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "143",
      par_relative_score: "+1",
      points_earned: 0,
    },
    {
      p_id: "27129",
      player_name: "Luke List",
      position: "CUT",
      round_1: "68",
      round_2: "75",
      round_3: null,
      round_4: null,
      total: "143",
      par_relative_score: "+1",
      points_earned: 0,
    },
    {
      p_id: "24924",
      player_name: "Bill Haas",
      position: "CUT",
      round_1: "73",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "28420",
      player_name: "Ryan Brehm",
      position: "CUT",
      round_1: "72",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "32150",
      player_name: "Michael Thompson",
      position: "CUT",
      round_1: "74",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "48887",
      player_name: "Matt Wallace",
      position: "CUT",
      round_1: "74",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "49960",
      player_name: "Sepp Straka",
      position: "CUT",
      round_1: "69",
      round_2: "75",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "50095",
      player_name: "Austin Smotherman",
      position: "CUT",
      round_1: "71",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "46435",
      player_name: "Austin Cook",
      position: "CUT",
      round_1: "71",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "144",
      par_relative_score: "+2",
      points_earned: 0,
    },
    {
      p_id: "48867",
      player_name: "Matti Schmid",
      position: "CUT",
      round_1: "74",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "49766",
      player_name: "Hank Lebioda",
      position: "CUT",
      round_1: "75",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "52372",
      player_name: "Cameron Champ",
      position: "CUT",
      round_1: "74",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "32139",
      player_name: "Danny Willett",
      position: "W/D",
      round_1: "73",
      round_2: null,
      round_3: null,
      round_4: null,
      total: "73",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "32662",
      player_name: "Michael Gligic",
      position: "CUT",
      round_1: "73",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "24925",
      player_name: "Jonathan Byrd",
      position: "CUT",
      round_1: "72",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "58168",
      player_name: "Davis Thompson",
      position: "CUT",
      round_1: "75",
      round_2: "70",
      round_3: null,
      round_4: null,
      total: "145",
      par_relative_score: "+3",
      points_earned: 0,
    },
    {
      p_id: "63457",
      player_name: "Palmer Jackson",
      position: "CUT",
      round_1: "73",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "146",
      par_relative_score: "+4",
      points_earned: 0,
    },
    {
      p_id: "12794",
      player_name: "Tim Weinhart",
      position: "CUT",
      round_1: "75",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "146",
      par_relative_score: "+4",
      points_earned: 0,
    },
    {
      p_id: "32366",
      player_name: "Kevin Chappell",
      position: "CUT",
      round_1: "71",
      round_2: "75",
      round_3: null,
      round_4: null,
      total: "146",
      par_relative_score: "+4",
      points_earned: 0,
    },
    {
      p_id: "49947",
      player_name: "Taylor Moore",
      position: "CUT",
      round_1: "72",
      round_2: "74",
      round_3: null,
      round_4: null,
      total: "146",
      par_relative_score: "+4",
      points_earned: 0,
    },
    {
      p_id: "36724",
      player_name: "Augusto Núñez",
      position: "CUT",
      round_1: "71",
      round_2: "75",
      round_3: null,
      round_4: null,
      total: "146",
      par_relative_score: "+4",
      points_earned: 0,
    },
    {
      p_id: "46601",
      player_name: "Trey Mullinax",
      position: "W/D",
      round_1: "75",
      round_2: null,
      round_3: null,
      round_4: null,
      total: "75",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "51950",
      player_name: "Max McGreevy",
      position: "CUT",
      round_1: "73",
      round_2: "74",
      round_3: null,
      round_4: null,
      total: "147",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "23325",
      player_name: "Vaughn Taylor",
      position: "CUT",
      round_1: "78",
      round_2: "69",
      round_3: null,
      round_4: null,
      total: "147",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "29479",
      player_name: "Scott Brown",
      position: "CUT",
      round_1: "76",
      round_2: "71",
      round_3: null,
      round_4: null,
      total: "147",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "27554",
      player_name: "Scott Harrington",
      position: "CUT",
      round_1: "73",
      round_2: "74",
      round_3: null,
      round_4: null,
      total: "147",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "58967",
      player_name: "Trevor Werbylo",
      position: "CUT",
      round_1: "74",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "147",
      par_relative_score: "+5",
      points_earned: 0,
    },
    {
      p_id: "31560",
      player_name: "Brian Stuard",
      position: "CUT",
      round_1: "76",
      round_2: "72",
      round_3: null,
      round_4: null,
      total: "148",
      par_relative_score: "+6",
      points_earned: 0,
    },
    {
      p_id: "54813",
      player_name: "Philip Knowles",
      position: "CUT",
      round_1: "71",
      round_2: "77",
      round_3: null,
      round_4: null,
      total: "148",
      par_relative_score: "+6",
      points_earned: 0,
    },
    {
      p_id: "36326",
      player_name: "David Lipsky",
      position: "W/D",
      round_1: "76",
      round_2: null,
      round_3: null,
      round_4: null,
      total: "76",
      par_relative_score: "+6",
      points_earned: 0,
    },
    {
      p_id: "47128",
      player_name: "Richy Werenski",
      position: "CUT",
      round_1: "74",
      round_2: "75",
      round_3: null,
      round_4: null,
      total: "149",
      par_relative_score: "+7",
      points_earned: 0,
    },
    {
      p_id: "31577",
      player_name: "Tano Goya",
      position: "CUT",
      round_1: "76",
      round_2: "73",
      round_3: null,
      round_4: null,
      total: "149",
      par_relative_score: "+7",
      points_earned: 0,
    },
    {
      p_id: "56320",
      player_name: "Bryson Nimmer",
      position: "CUT",
      round_1: "73",
      round_2: "78",
      round_3: null,
      round_4: null,
      total: "151",
      par_relative_score: "+9",
      points_earned: 0,
    },
  ],
};
